import { Card } from './Card';

export const CARDS: Card[] = [
    {
    "id": 1,
    "cardId": 26000021,
    "cardName": "Hog Rider",
    "elixir": 4,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Buildings",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 2,
    "cardId": 27000000,
    "cardName": "Cannon",
    "elixir": 3,
    "cardType": "building",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 3,
    "cardId": 26000010,
    "cardName": "Skeletons",
    "elixir": 1,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 4,
    "cardId": 26000030,
    "cardName": "Ice Spirit",
    "elixir": 1,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 5,
    "cardId": 26000000,
    "cardName": "Knight",
    "elixir": 3,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 6,
    "cardId": 26000014,
    "cardName": "Musketeer",
    "elixir": 4,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 7,
    "cardId": 28000008,
    "cardName": "Zap",
    "elixir": 2,
    "cardType": "spell",
    "travels": "Anywhere",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 8,
    "cardId": 28000003,
    "cardName": "Rocket",
    "elixir": 6,
    "cardType": "spell",
    "travels": "Air",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 9,
    "cardId": 26000007,
    "cardName": "Witch",
    "elixir": 5,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "Yes",
    "spawner": "Yes",
    "rangeLevel": 2
    },
    {
    "id": 10,
    "cardId": 26000011,
    "cardName": "Valkyrie",
    "elixir": 4,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 11,
    "cardId": 28000004,
    "cardName": "Goblin Barrel",
    "elixir": 3,
    "cardType": "spell",
    "travels": "Air",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 12,
    "cardId": 26000045,
    "cardName": "Executioner",
    "elixir": 5,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 13,
    "cardId": 26000004,
    "cardName": "P.E.K.K.A",
    "elixir": 7,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 14,
    "cardId": 26000012,
    "cardName": "Skeleton Army",
    "elixir": 3,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 15,
    "cardId": 26000026,
    "cardName": "Princess",
    "elixir": 3,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 16,
    "cardId": 28000011,
    "cardName": "The Log",
    "elixir": 2,
    "cardType": "spell",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 17,
    "cardId": 26000041,
    "cardName": "Goblin Gang",
    "elixir": 3,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 18,
    "cardId": 27000003,
    "cardName": "Inferno Tower",
    "elixir": 5,
    "cardType": "building",
    "travels": "NA",
    "targets": "Ground",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 19,
    "cardId": 26000051,
    "cardName": "Ram Rider",
    "elixir": 5,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Buildings",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 20,
    "cardId": 26000035,
    "cardName": "Lumberjack",
    "elixir": 4,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 21,
    "cardId": 26000049,
    "cardName": "Bats",
    "elixir": 2,
    "cardType": "character",
    "travels": "Air",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 22,
    "cardId": 26000037,
    "cardName": "Inferno Dragon",
    "elixir": 4,
    "cardType": "character",
    "travels": "Air",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 23,
    "cardId": 26000038,
    "cardName": "Ice Golem",
    "elixir": 2,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Buildings",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 24,
    "cardId": 28000017,
    "cardName": "Giant Snowball",
    "elixir": 2,
    "cardType": "spell",
    "travels": "Air",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 25,
    "cardId": 28000009,
    "cardName": "Poison",
    "elixir": 4,
    "cardType": "spell",
    "travels": "Anywhere",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 26,
    "cardId": 28000001,
    "cardName": "Arrows",
    "elixir": 3,
    "cardType": "spell",
    "travels": "Air",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 27,
    "cardId": 28000002,
    "cardName": "Rage",
    "elixir": 2,
    "cardType": "spell",
    "travels": "Anywhere",
    "targets": "All Allies",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 28,
    "cardId": 26000020,
    "cardName": "Giant Skeleton",
    "elixir": 6,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 29,
    "cardId": 26000055,
    "cardName": "Mega Knight",
    "elixir": 7,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 30,
    "cardId": 26000022,
    "cardName": "Minion Horde",
    "elixir": 5,
    "cardType": "character",
    "travels": "Air",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 31,
    "cardId": 28000010,
    "cardName": "Graveyard",
    "elixir": 5,
    "cardType": "spell",
    "travels": "Anywhere",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "Yes",
    "rangeLevel": 3
    },
    {
    "id": 32,
    "cardId": 28000015,
    "cardName": "Barbarian Barrel",
    "elixir": 2,
    "cardType": "spell",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 33,
    "cardId": 26000039,
    "cardName": "Mega Minion",
    "elixir": 3,
    "cardType": "character",
    "travels": "Air",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 34,
    "cardId": 26000027,
    "cardName": "Dark Prince",
    "elixir": 4,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 35,
    "cardId": 26000029,
    "cardName": "Lava Hound",
    "elixir": 7,
    "cardType": "character",
    "travels": "Air",
    "targets": "Buildings",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 36,
    "cardId": 26000057,
    "cardName": "Flying Machine",
    "elixir": 4,
    "cardType": "character",
    "travels": "Air",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 37,
    "cardId": 28000013,
    "cardName": "Clone",
    "elixir": 3,
    "cardType": "spell",
    "travels": "Anywhere",
    "targets": "Ally Characters",
    "attackAir": "NA",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 38,
    "cardId": 26000015,
    "cardName": "Baby Dragon",
    "elixir": 4,
    "cardType": "character",
    "travels": "Air",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 39,
    "cardId": 28000000,
    "cardName": "Fireball",
    "elixir": 4,
    "cardType": "spell",
    "travels": "Air",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 40,
    "cardId": 26000032,
    "cardName": "Miner",
    "elixir": 3,
    "cardType": "spell",
    "travels": "Anywhere",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 41,
    "cardId": 26000044,
    "cardName": "Hunter",
    "elixir": 4,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Air",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 42,
    "cardId": 27000002,
    "cardName": "Mortar",
    "elixir": 4,
    "cardType": "building",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 43,
    "cardId": 26000023,
    "cardName": "Ice Wizard",
    "elixir": 3,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 44,
    "cardId": 27000009,
    "cardName": "Tombstone",
    "elixir": 3,
    "cardType": "building",
    "travels": "NA",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "Yes",
    "rangeLevel": 1
    },
    {
    "id": 45,
    "cardId": 28000012,
    "cardName": "Tornado",
    "elixir": 3,
    "cardType": "spell",
    "travels": "Anywhere",
    "targets": "Characters",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 46,
    "cardId": 26000031,
    "cardName": "Fire Spirits",
    "elixir": 2,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 47,
    "cardId": 28000007,
    "cardName": "Lightning",
    "elixir": 6,
    "cardType": "spell",
    "travels": "Anywhere",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 48,
    "cardId": 26000017,
    "cardName": "Wizard",
    "elixir": 5,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 49,
    "cardId": 26000009,
    "cardName": "Golem",
    "elixir": 8,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Buildings",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 50,
    "cardId": 26000016,
    "cardName": "Prince",
    "elixir": 4,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 51,
    "cardId": 26000042,
    "cardName": "Electro Wizard",
    "elixir": 3,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 52,
    "cardId": 27000008,
    "cardName": "X-Bow",
    "elixir": 6,
    "cardType": "building",
    "travels": "NA",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 53,
    "cardId": 26000006,
    "cardName": "Balloon",
    "elixir": 5,
    "cardType": "character",
    "travels": "Air",
    "targets": "Buildings",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 54,
    "cardId": 26000008,
    "cardName": "Barbarians",
    "elixir": 5,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 55,
    "cardId": 26000053,
    "cardName": "Rascals",
    "elixir": 5,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 56,
    "cardId": 26000046,
    "cardName": "Bandit",
    "elixir": 3,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 57,
    "cardId": 26000001,
    "cardName": "Archers",
    "elixir": 3,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 58,
    "cardId": 27000006,
    "cardName": "Tesla",
    "elixir": 4,
    "cardType": "building",
    "travels": "NA",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 59,
    "cardId": 28000005,
    "cardName": "Freeze",
    "elixir": 4,
    "cardType": "spell",
    "travels": "Anywhere",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 3
    },
    {
    "id": 60,
    "cardId": 26000060,
    "cardName": "Goblin Giant",
    "elixir": 6,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Buildings",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 61,
    "cardId": 26000033,
    "cardName": "Sparky",
    "elixir": 6,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 62,
    "cardId": 26000018,
    "cardName": "Mini P.E.K.K.A",
    "elixir": 4,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 63,
    "cardId": 26000062,
    "cardName": "Magic Archer",
    "elixir": 4,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 64,
    "cardId": 26000005,
    "cardName": "Minions",
    "elixir": 3,
    "cardType": "character",
    "travels": "Air",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 65,
    "cardId": 26000036,
    "cardName": "Battle Ram",
    "elixir": 4,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Buildings",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 66,
    "cardId": 26000048,
    "cardName": "Night Witch",
    "elixir": 4,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "Yes",
    "spawner": "Yes",
    "rangeLevel": 2
    },
    {
    "id": 67,
    "cardId": 27000010,
    "cardName": "Furnace",
    "elixir": 4,
    "cardType": "building",
    "travels": "NA",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "Yes",
    "rangeLevel": 1
    },
    {
    "id": 68,
    "cardId": 26000050,
    "cardName": "Royal Ghost",
    "elixir": 3,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "Yes",
    "spawner": "",
    "rangeLevel": 1
    },
    {
    "id": 69,
    "cardId": 27000001,
    "cardName": "Goblin Hut",
    "elixir": 5,
    "cardType": "building",
    "travels": "NA",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "Yes",
    "rangeLevel": 1
    },
    {
    "id": 70,
    "cardId": 26000040,
    "cardName": "Dart Goblin",
    "elixir": 3,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 71,
    "cardId": 26000056,
    "cardName": "Skeleton Barrel",
    "elixir": 3,
    "cardType": "spell",
    "travels": "Air",
    "targets": "Buildings",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 72,
    "cardId": 26000013,
    "cardName": "Bomber",
    "elixir": 3,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 73,
    "cardId": 26000025,
    "cardName": "Guards",
    "elixir": 3,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 74,
    "cardId": 26000019,
    "cardName": "Spear Goblins",
    "elixir": 2,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 75,
    "cardId": 26000028,
    "cardName": "Three Musketeers",
    "elixir": 9,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 76,
    "cardId": 27000007,
    "cardName": "Elixir Collector",
    "elixir": 6,
    "cardType": "building",
    "travels": "NA",
    "targets": "Allies",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 77,
    "cardId": 26000043,
    "cardName": "Elite Barbarians",
    "elixir": 6,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 78,
    "cardId": 26000024,
    "cardName": "Royal Giant",
    "elixir": 6,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Buildings",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 79,
    "cardId": 26000052,
    "cardName": "Zappies",
    "elixir": 4,
    "cardType": "character",
    "travels": "Ground",
    "targets": "All",
    "attackAir": "Yes",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 80,
    "cardId": 26000002,
    "cardName": "Goblins",
    "elixir": 2,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 81,
    "cardId": 27000012,
    "cardName": "Goblin Cage",
    "elixir": 4,
    "cardType": "building",
    "travels": "NA",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 1
    },
    {
    "id": 82,
    "cardId": 26000034,
    "cardName": "Bowler",
    "elixir": 5,
    "cardType": "character",
    "travels": "Ground",
    "targets": "Ground",
    "attackAir": "No",
    "spawner": "No",
    "rangeLevel": 2
    },
    {
    "id": 83,
    "cardId": 28000006,
    "cardName": "Mirror",
    "elixir": 0,
    "cardType": "Spell",
    "travels": "NA",
    "targets": "NA",
    "attackAir": "NA",
    "spawner": "NA",
    "rangeLevel": 0
    }
    ];